name: f110_ope_benchmark
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.18
  - zarr=2.16.1
  - tqdm
  - numpy=1.22
  - absl-py=2.0.0
  - pytorch=2.3.0=py3.8_cuda11.8_cudnn8.7.0_0
  - tensorboardX
  - seaborn